apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: $ACRNAME.azurecr.io/mywebapp:0.1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: mywebapp
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mywebapp-scaledobject
  namespace: $NAMESPACE
  labels:
    deploymentName: mywebapp
spec:
  scaleTargetRef:
    name: mywebapp
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.$NAMESPACE.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: "10"
        query: sum(rate(nginx_ingress_controller_requests{service="mywebapp"}[1m]))
        namespace: $NAMESPACE
